import path from "node:path";
import fs from "node:fs/promises";

/**
 * Initializes the server directory and basic files if they don't exist
 * @returns {Promise<boolean>} Success status
 */
async function initializeServerDirectory() {
  const serverDir = "./server";

  try {
    // Check if server directory exists
    try {
      await fs.access(serverDir);
      console.log("Server directory already exists");
    } catch (error) {
      // Directory doesn't exist, create it
      console.log("Creating server directory...");
      await fs.mkdir(serverDir);
      console.log("Server directory created successfully");
    }

    // Create default server.properties if it doesn't exist
    const propsPath = path.join(serverDir, "server.properties");
    try {
      await fs.access(propsPath);
      console.log("server.properties already exists");
    } catch (error) {
      // Create default server.properties
      console.log("Creating default server.properties...");
      const defaultProps = `# Minecraft server properties
# Generated by Minecraft Manager
server-port=25565
gamemode=survival
difficulty=normal
level-name=world
pvp=true
online-mode=true
`;
      await fs.writeFile(propsPath, defaultProps);
      console.log("Default server.properties created");
    }

    return true;
  } catch (error) {
    console.error("Error initializing server directory:", error);
    return false;
  }
}

export { initializeServerDirectory };
